Custom post-processor
bcdev/nc2zarr pull request #22
Opened 2021-03-12 15:25 UTC by forman

Closes #21

* You can now provide your Python code for customization 
  of the datasets read and written. (#16)
  - `input/custom_preprocessor: "module:function"` is called on 
    each input after optional variable selection.
  - `process/custom_processor: "module:function"` is called after 
    optional renaming and before optional rechunking.
  - **`output/custom_postprocessor: "module:function"` is called before 
    the final dataset is written. (#21)**

  **All three** `"function"`s are expected to receive an `xarray.Dataset` object
  as only argument and return the same or modified `xarray.Dataset` object.
  Note: to let Python import `"module"` that is not a user package,
  you can extend the `PYTHONPATH` environment variable before
  calling `nc2zarr`:
    ```
    export PYTHONPATH=${PYTHONPATH}:path/to/my/modules
    nc2zarr ...
    ```

2021-03-12 16:44 UTC, TonioF requested changes
Test don't work.

2021-03-12 16:44 UTC, TonioF commented on nc2zarr/res/config-template.yml
> +  # An optional, custom preprocessor.
```suggestion
  # An optional custom preprocessor.
```

2021-03-12 16:44 UTC, TonioF commented on nc2zarr/res/config-template.yml
> +  # An optional, custom processor.
```suggestion
  # An optional custom processor.
```

2021-03-12 16:44 UTC, TonioF commented on nc2zarr/res/config-template.yml
> +  # An optional, custom post-processor.
```suggestion
  # An optional custom post-processor.
```

2021-03-13 16:56 UTC, forman commented
sorry @pont-us, I have to carry on

2021-03-13 16:56 UTC, merged